services:
  nlw-agents-pg:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: agents
    ports:
      # porta de entrada do banco para porta do docker
      - '5432:5432'
    volumes:
      # joga o setup sql para o setup do docker assim que subir o container
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
